//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Social.Data.WebAPI.DatabaseContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Commitment
    {
        public Commitment()
        {
            this.AccountCommitmentLinks = new HashSet<AccountCommitmentLink>();
            this.CommitmentNotes = new HashSet<CommitmentNote>();
            this.CommitmentQuestionnaireLinks = new HashSet<CommitmentQuestionnaireLink>();
            this.RCAccountTransactions = new HashSet<RCAccountTransaction>();
        }
    
        public System.Guid CommitmentID { get; set; }
        public System.Guid CommitmentGroupID { get; set; }
        public System.Guid ParentCommitmentID { get; set; }
        public System.Guid CommitmentTypeID { get; set; }
        public System.Guid CommitmentStatusTypeID { get; set; }
        public System.Guid CommitmentTypeSubTypeID { get; set; }
        public System.Guid AccountID { get; set; }
        public string Title { get; set; }
        public string Name { get; set; }
        public string Details { get; set; }
        public System.DateTime StartDateTime { get; set; }
        public System.DateTime EndDateTime { get; set; }
        public int RevisionNumber { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual ICollection<AccountCommitmentLink> AccountCommitmentLinks { get; set; }
        public virtual CommitmentGroup CommitmentGroup { get; set; }
        public virtual CommitmentStatusType CommitmentStatusType { get; set; }
        public virtual CommitmentType CommitmentType { get; set; }
        public virtual CommitmentTypeSubType CommitmentTypeSubType { get; set; }
        public virtual ICollection<CommitmentNote> CommitmentNotes { get; set; }
        public virtual ICollection<CommitmentQuestionnaireLink> CommitmentQuestionnaireLinks { get; set; }
        public virtual ICollection<RCAccountTransaction> RCAccountTransactions { get; set; }
    }
}
