//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Social.Data.WebAPI.DatabaseContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupAccount
    {
        public GroupAccount()
        {
            this.AccountCommitmentLinks = new HashSet<AccountCommitmentLink>();
            this.AccountGroupAccountLinks = new HashSet<AccountGroupAccountLink>();
            this.GroupAccountGroupAccountSettingsLinks = new HashSet<GroupAccountGroupAccountSettingsLink>();
            this.GroupAccountMetaDatas = new HashSet<GroupAccountMetaData>();
            this.QuestionnaireQuestionQuestionnaireQuestionMultichoiceAnswerLinks = new HashSet<QuestionnaireQuestionQuestionnaireQuestionMultichoiceAnswerLink>();
            this.QuestionnaireQuestions = new HashSet<QuestionnaireQuestion>();
            this.QuestionnaireQuestionMultichoiceAnswers = new HashSet<QuestionnaireQuestionMultichoiceAnswer>();
            this.RCAccountTransactions = new HashSet<RCAccountTransaction>();
            this.RCAccountTransactions1 = new HashSet<RCAccountTransaction>();
        }
    
        public System.Guid GroupAccountID { get; set; }
        public System.Guid GroupAccountTypeID { get; set; }
        public System.Guid PaymentPlanGroupAccountID { get; set; }
        public string Name { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
    
        public virtual ICollection<AccountCommitmentLink> AccountCommitmentLinks { get; set; }
        public virtual ICollection<AccountGroupAccountLink> AccountGroupAccountLinks { get; set; }
        public virtual GroupAccountType GroupAccountType { get; set; }
        public virtual PaymentPlanGroupAccount PaymentPlanGroupAccount { get; set; }
        public virtual ICollection<GroupAccountGroupAccountSettingsLink> GroupAccountGroupAccountSettingsLinks { get; set; }
        public virtual ICollection<GroupAccountMetaData> GroupAccountMetaDatas { get; set; }
        public virtual ICollection<QuestionnaireQuestionQuestionnaireQuestionMultichoiceAnswerLink> QuestionnaireQuestionQuestionnaireQuestionMultichoiceAnswerLinks { get; set; }
        public virtual ICollection<QuestionnaireQuestion> QuestionnaireQuestions { get; set; }
        public virtual ICollection<QuestionnaireQuestionMultichoiceAnswer> QuestionnaireQuestionMultichoiceAnswers { get; set; }
        public virtual ICollection<RCAccountTransaction> RCAccountTransactions { get; set; }
        public virtual ICollection<RCAccountTransaction> RCAccountTransactions1 { get; set; }
    }
}
