//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Social.Data.WebAPI.DatabaseContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupAccountSettingsType
    {
        public GroupAccountSettingsType()
        {
            this.GroupAccountGroupAccountSettingsLinks = new HashSet<GroupAccountGroupAccountSettingsLink>();
            this.GroupAccountSettings = new HashSet<GroupAccountSetting>();
        }
    
        public System.Guid GroupAccountSettingsTypeID { get; set; }
        public string Type { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
    
        public virtual ICollection<GroupAccountGroupAccountSettingsLink> GroupAccountGroupAccountSettingsLinks { get; set; }
        public virtual ICollection<GroupAccountSetting> GroupAccountSettings { get; set; }
    }
}
