//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Social.Data.WebAPI.DatabaseContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentPlanAccountFee
    {
        public System.Guid PaymentPlanAccountFeeID { get; set; }
        public System.Guid PaymentPlanAccountID { get; set; }
        public string Section { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
    
        public virtual PaymentPlanAccount PaymentPlanAccount { get; set; }
    }
}
