//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Social.Data.WebAPI.DatabaseContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Questionnaire
    {
        public Questionnaire()
        {
            this.CommitmentQuestionnaireLinks = new HashSet<CommitmentQuestionnaireLink>();
            this.QuestionnaireQuestionnaireQuestionLinks = new HashSet<QuestionnaireQuestionnaireQuestionLink>();
        }
    
        public System.Guid QuestionnaireID { get; set; }
        public System.Guid QuestionnaireTypeID { get; set; }
        public string Name { get; set; }
        public string Details { get; set; }
        public System.DateTime SendDate { get; set; }
        public System.DateTime ClosedDate { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
    
        public virtual ICollection<CommitmentQuestionnaireLink> CommitmentQuestionnaireLinks { get; set; }
        public virtual QuestionnaireType QuestionnaireType { get; set; }
        public virtual ICollection<QuestionnaireQuestionnaireQuestionLink> QuestionnaireQuestionnaireQuestionLinks { get; set; }
    }
}
