//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Social.Data.WebAPI.DatabaseContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionnaireQuestionnaireQuestionLink
    {
        public System.Guid QuestionnaireQuestionnaireQuestionLinkID { get; set; }
        public System.Guid CommitmentGroupID { get; set; }
        public System.Guid QuestionnaireID { get; set; }
        public System.Guid QuestionnaireQuestionID { get; set; }
        public int RevisonNumber { get; set; }
        public int SortOrder { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
    
        public virtual CommitmentGroup CommitmentGroup { get; set; }
        public virtual Questionnaire Questionnaire { get; set; }
        public virtual QuestionnaireQuestion QuestionnaireQuestion { get; set; }
    }
}
