//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Social.Data.WebAPI.DatabaseContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionnaireQuestion
    {
        public QuestionnaireQuestion()
        {
            this.QuestionnaireQuestionQuestionnaireQuestionMultichoiceAnswerLinks = new HashSet<QuestionnaireQuestionQuestionnaireQuestionMultichoiceAnswerLink>();
            this.QuestionnaireQuestionnaireQuestionLinks = new HashSet<QuestionnaireQuestionnaireQuestionLink>();
        }
    
        public System.Guid QuestionnaireQuestionID { get; set; }
        public System.Guid QuestionnaireQuestionTypeID { get; set; }
        public System.Guid AccountID { get; set; }
        public System.Guid GroupAccountID { get; set; }
        public System.Guid CommitmentGroupID { get; set; }
        public System.Guid QuestionnaireQuestionAnswerTypeID { get; set; }
        public string Name { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual CommitmentGroup CommitmentGroup { get; set; }
        public virtual GroupAccount GroupAccount { get; set; }
        public virtual ICollection<QuestionnaireQuestionQuestionnaireQuestionMultichoiceAnswerLink> QuestionnaireQuestionQuestionnaireQuestionMultichoiceAnswerLinks { get; set; }
        public virtual QuestionnaireQuestionAnswerType QuestionnaireQuestionAnswerType { get; set; }
        public virtual QuestionnaireQuestionAnswerType QuestionnaireQuestionAnswerType1 { get; set; }
        public virtual ICollection<QuestionnaireQuestionnaireQuestionLink> QuestionnaireQuestionnaireQuestionLinks { get; set; }
    }
}
