//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Social.Data.DatabaseContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountAccountSettingsLink
    {
        public System.Guid AccountAccountSettingsLinkID { get; set; }
        public System.Guid AccountID { get; set; }
        public System.Guid AccountSettingsID { get; set; }
        public System.Guid AccountSettingsTypeID { get; set; }
        public string Value { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual AccountSetting AccountSetting { get; set; }
        public virtual AccountSettingsType AccountSettingsType { get; set; }
    }
}
