//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Social.Data.DatabaseContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public Account()
        {
            this.AccountAccountSettingsLinks = new HashSet<AccountAccountSettingsLink>();
            this.AccountCommitmentLinks = new HashSet<AccountCommitmentLink>();
            this.AccountGroupAccountLinks = new HashSet<AccountGroupAccountLink>();
            this.AccountMetaDatas = new HashSet<AccountMetaData>();
            this.Commitments = new HashSet<Commitment>();
            this.CommitmentNotes = new HashSet<CommitmentNote>();
            this.CommitmentQuestionnaireLinks = new HashSet<CommitmentQuestionnaireLink>();
            this.CommitmentQuestionnaireLinks1 = new HashSet<CommitmentQuestionnaireLink>();
            this.QuestionnaireQuestionQuestionnaireQuestionMultichoiceAnswerLinks = new HashSet<QuestionnaireQuestionQuestionnaireQuestionMultichoiceAnswerLink>();
            this.QuestionnaireQuestions = new HashSet<QuestionnaireQuestion>();
            this.QuestionnaireQuestionMultichoiceAnswers = new HashSet<QuestionnaireQuestionMultichoiceAnswer>();
            this.RCAccountBalances = new HashSet<RCAccountBalance>();
            this.RCAccountTransactions = new HashSet<RCAccountTransaction>();
            this.RCAccountTransactions1 = new HashSet<RCAccountTransaction>();
        }
    
        public System.Guid AccountID { get; set; }
        public System.Guid AccountTypeID { get; set; }
        public System.Guid PaymentPlanAccountID { get; set; }
        public string Email { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual AccountType AccountType { get; set; }
        public virtual PaymentPlanAccount PaymentPlanAccount { get; set; }
        public virtual ICollection<AccountAccountSettingsLink> AccountAccountSettingsLinks { get; set; }
        public virtual ICollection<AccountCommitmentLink> AccountCommitmentLinks { get; set; }
        public virtual ICollection<AccountGroupAccountLink> AccountGroupAccountLinks { get; set; }
        public virtual ICollection<AccountMetaData> AccountMetaDatas { get; set; }
        public virtual ICollection<Commitment> Commitments { get; set; }
        public virtual ICollection<CommitmentNote> CommitmentNotes { get; set; }
        public virtual ICollection<CommitmentQuestionnaireLink> CommitmentQuestionnaireLinks { get; set; }
        public virtual ICollection<CommitmentQuestionnaireLink> CommitmentQuestionnaireLinks1 { get; set; }
        public virtual ICollection<QuestionnaireQuestionQuestionnaireQuestionMultichoiceAnswerLink> QuestionnaireQuestionQuestionnaireQuestionMultichoiceAnswerLinks { get; set; }
        public virtual ICollection<QuestionnaireQuestion> QuestionnaireQuestions { get; set; }
        public virtual ICollection<QuestionnaireQuestionMultichoiceAnswer> QuestionnaireQuestionMultichoiceAnswers { get; set; }
        public virtual ICollection<RCAccountBalance> RCAccountBalances { get; set; }
        public virtual ICollection<RCAccountTransaction> RCAccountTransactions { get; set; }
        public virtual ICollection<RCAccountTransaction> RCAccountTransactions1 { get; set; }
    }
}
