//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Social.Data.DatabaseContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommitmentTypeSubType
    {
        public CommitmentTypeSubType()
        {
            this.AccountCommitmentLinks = new HashSet<AccountCommitmentLink>();
            this.Commitments = new HashSet<Commitment>();
        }
    
        public System.Guid CommitmentTypeSubTypeID { get; set; }
        public System.Guid CommitmentTypeID { get; set; }
        public string Type { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual ICollection<AccountCommitmentLink> AccountCommitmentLinks { get; set; }
        public virtual ICollection<Commitment> Commitments { get; set; }
        public virtual CommitmentType CommitmentType { get; set; }
    }
}
