//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Social.Data.DatabaseContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommitmentNote
    {
        public CommitmentNote()
        {
            this.CommitmentNote1 = new HashSet<CommitmentNote>();
        }
    
        public System.Guid CommitmentNoteID { get; set; }
        public System.Guid CommitmentGroupID { get; set; }
        public System.Guid CommitmentID { get; set; }
        public System.Guid CommitmentNoteTypeID { get; set; }
        public System.Guid AccountID { get; set; }
        public System.Guid ParentCommitmentNoteID { get; set; }
        public string Name { get; set; }
        public string Details { get; set; }
        public int RevisionNumber { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Commitment Commitment { get; set; }
        public virtual CommitmentGroup CommitmentGroup { get; set; }
        public virtual CommitmentNoteType CommitmentNoteType { get; set; }
        public virtual ICollection<CommitmentNote> CommitmentNote1 { get; set; }
        public virtual CommitmentNote CommitmentNote2 { get; set; }
    }
}
