//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Social.Data.DatabaseContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentPlanAccount
    {
        public PaymentPlanAccount()
        {
            this.Accounts = new HashSet<Account>();
            this.PaymentPlanAccountFees = new HashSet<PaymentPlanAccountFee>();
        }
    
        public System.Guid PaymentPlanAccountID { get; set; }
        public string Name { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual ICollection<Account> Accounts { get; set; }
        public virtual ICollection<PaymentPlanAccountFee> PaymentPlanAccountFees { get; set; }
    }
}
