//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Social.Data.DatabaseContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentPlanGroupAccountFee
    {
        public System.Guid PaymentPlanGroupAccountFeeID { get; set; }
        public System.Guid PaymentPlanGroupAccountID { get; set; }
        public string Section { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual PaymentPlanGroupAccount PaymentPlanGroupAccount { get; set; }
    }
}
