//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Social.Data.DatabaseContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionnaireQuestionQuestionnaireQuestionMultichoiceAnswerLink
    {
        public System.Guid QuestionnaireQuestionQuestionnaireQuestionMultichoiceAnswerLinkID { get; set; }
        public System.Guid QuestionnaireQuestionID { get; set; }
        public System.Guid QuestionnaireQuestionMultichoiceAnswerID { get; set; }
        public System.Guid AccountID { get; set; }
        public System.Guid GroupAccountID { get; set; }
        public System.Guid CommitmentGroupID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual CommitmentGroup CommitmentGroup { get; set; }
        public virtual GroupAccount GroupAccount { get; set; }
        public virtual QuestionnaireQuestion QuestionnaireQuestion { get; set; }
        public virtual QuestionnaireQuestionMultichoiceAnswer QuestionnaireQuestionMultichoiceAnswer { get; set; }
    }
}
