//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Social.Data.DatabaseContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class RCAccountTransaction
    {
        public System.Guid RCAccountTransactionID { get; set; }
        public System.Guid ReceiverGroupAccountID { get; set; }
        public System.Guid ReceiverAccountID { get; set; }
        public System.Guid GrantorGroupAccountID { get; set; }
        public System.Guid GrantorAccountID { get; set; }
        public System.Guid CommitmentGroupID { get; set; }
        public System.Guid CommitmentID { get; set; }
        public int TransactionAmount { get; set; }
        public int AccountTotal { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Account Account1 { get; set; }
        public virtual Commitment Commitment { get; set; }
        public virtual CommitmentGroup CommitmentGroup { get; set; }
        public virtual GroupAccount GroupAccount { get; set; }
        public virtual GroupAccount GroupAccount1 { get; set; }
    }
}
