//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Social.Data.DatabaseContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class SDBOScriptsRun
    {
        public long id { get; set; }
        public Nullable<long> version_id { get; set; }
        public string script_name { get; set; }
        public string text_of_script { get; set; }
        public string text_hash { get; set; }
        public Nullable<bool> one_time_script { get; set; }
        public Nullable<System.DateTime> entry_date { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public string entered_by { get; set; }
    }
}
