<?xml version="1.0" encoding="utf-8"?><Database Name="DB_9B3681_BETA" Class="BetaDatabaseDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=SQL5013.Smarterasp.net;Initial Catalog=DB_9B3681_BETA;User ID=DB_9B3681_BETA_admin" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="DB_9B3681_BETAConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.BetaSignUp" Member="BetaSignUps">
    <Type Name="BetaSignUp">
      <Column Name="BetaSignUpID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.ContactUs" Member="ContactUs">
    <Type Name="ContactUs">
      <Column Name="ContactUsID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Phone" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Message" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>